-- Archivos de configuración basicos
require('settings')
require('keymaps')
require('packer-config')

-- Plugins
require('plugins/Theme')
require('plugins/lualine')
require('plugins/buffer-line')
require('plugins/nvim-tree')
require('plugins/autopairs')
require('plugins/nvim-treesitter')
-- require('plugins/coc-config')
require('plugins/nvim-lspconfig')
require('plugins/luaSnip')
require('plugins/nvim-cmp')
require('plugins/emmet')
require('plugins/identline')
require('plugins/null-ls')
require('plugins/postman')
